In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv('full_df.csv')

In [4]:
df.drop('Unnamed: 0', axis=1, inplace=True)

In [6]:
df.columns

Index(['State', 'Code', 'y2000', 'y2001', 'y2002', 'y2003', 'y2004', 'y2005',
       'y2006', 'y2007', 'y2008', 'y2009', 'y2010', 'y2011', 'y2012', 'y2013',
       'y2014', 'y2015', 'y2016', 'y2017', 'y2018', 'y2019'],
      dtype='object')

In [10]:
df.columns = ['State', 'state_code', 'y2000', 'y2001', 'y2002', 'y2003', 'y2004', 'y2005',
       'y2006', 'y2007', 'y2008', 'y2009', 'y2010', 'y2011', 'y2012', 'y2013',
       'y2014', 'y2015', 'y2016', 'y2017', 'y2018', 'y2019']

In [11]:
df.columns

Index(['State', 'state_code', 'y2000', 'y2001', 'y2002', 'y2003', 'y2004',
       'y2005', 'y2006', 'y2007', 'y2008', 'y2009', 'y2010', 'y2011', 'y2012',
       'y2013', 'y2014', 'y2015', 'y2016', 'y2017', 'y2018', 'y2019'],
      dtype='object')

In [12]:
df.to_csv('spyder_df.csv')

In [21]:
df.head()

,State,state_code,y2000,y2001,y2002,y2003,y2004,y2005,y2006,y2007,...,y2010,y2011,y2012,y2013,y2014,y2015,y2016,y2017,y2018,y2019
0,Alabama,AL,6,10,11,8,6,3,11,13,...,2,24,25,24,64,25,38,41,36,66
1,Alaska,AK,2,2,3,3,3,4,3,10,...,7,11,10,14,8,9,15,10,11,3
2,Arizona,AZ,2,3,4,4,13,10,10,2,...,2,15,13,32,21,12,13,28,7,10
3,Arkansas,AR,7,4,3,0,0,0,0,1,...,0,0,0,0,0,0,2,6,4,18
4,California,CA,96,95,97,86,48,95,85,75,...,129,92,70,112,73,98,134,145,104,144

In [27]:
print(df.y2000.max())
print(df.y2001.max())
print(df.y2003.max())
print(df.y2004.max())
print(df.y2005.max())
print(df.y2006.max())
print(df.y2007.max())
print(df.y2008.max())
print(df.y2009.max())
print(df.y2010.max())
print(df.y2011.max())
print(df.y2012.max())
print(df.y2013.max())
print(df.y2014.max())
print(df.y2015.max())
print(df.y2016.max())
print(df.y2017.max())
print(df.y2018.max())
print(df.y2019.max())

4329
4083
5730
5100
5565
4460
4165
7794
5722
3805
5362
5138
5758
7487
9048
11443
11900
10208
8998

In [38]:
df = df.append({'State' : 'Total',
          'state_code' : '',
          'y2000' : '4083', 
          'y2001' : '5730',
          'y2002' : '5100',
          'y2003' : '5565',
          'y2004' : '4460',
          'y2005' : '4165',
          'y2006' : '7794',
          'y2007' : '5722',
          'y2008' : '3805',
          'y2009' : '5362',
          'y2009' : '5138',
          'y2009' : '5758',
          'y2019' : '7487',
          'y2000' : '9048',
          'y2000' : '11443', 
          'y2000' : '11900', 
          'y2000' : '10208', 
          'y2000' : '8998'},
         ignore_index=True)

df

,State,state_code,y2000,y2001,y2002,y2003,y2004,y2005,y2006,y2007,...,y2010,y2011,y2012,y2013,y2014,y2015,y2016,y2017,y2018,y2019
0,Alabama,AL,6,10,11,8,6,3,11,13,...,2.0,24.0,25.0,24.0,64.0,25.0,38.0,41.0,36.0,66
1,Alaska,AK,2,2,3,3,3,4,3,10,...,7.0,11.0,10.0,14.0,8.0,9.0,15.0,10.0,11.0,3
2,Arizona,AZ,2,3,4,4,13,10,10,2,...,2.0,15.0,13.0,32.0,21.0,12.0,13.0,28.0,7.0,10
3,Arkansas,AR,7,4,3,0,0,0,0,1,...,0.0,0.0,0.0,0.0,0.0,0.0,2.0,6.0,4.0,18
4,California,CA,96,95,97,86,48,95,85,75,...,129.0,92.0,70.0,112.0,73.0,98.0,134.0,145.0,104.0,144
5,Colorado,CO,0,0,1,0,0,0,0,0,...,3.0,0.0,0.0,0.0,0.0,0.0,0.0,4.0,3.0,8
6,Connecticut,CT,3773,3597,4631,1403,1348,1810,1788,3058,...,3068.0,3039.0,2657.0,2925.0,2360.0,2541.0,1748.0,2051.0,1859.0,1233
7,Delaware,DE,167,152,194,212,339,646,482,715,...,656.0,873.0,669.0,509.0,417.0,435.0,506.0,608.0,520.0,641
8,District of Columbia,DC,11,17,25,14,16,10,62,116,...,42.0,0.0,0.0,35.0,40.0,121.0,103.0,84.0,79.0,100
9,Florida,FL,54,43,79,43,46,47,34,30,...,84.0,115.0,118.0,138.0,155.0,166.0,216.0,210.0,169.0,162
10,Georgia,GA,0,0,2,10,12,6,8,11,...,10.0,32.0,31.0,8.0,4.0,8.0,4.0,8.0,19.0,18
11,Hawaii,HI,0,0,0,0,0,0,0,0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0
12,Idaho,ID,4,5,4,3,6,2,7,9,...,9.0,4.0,5.0,19.0,9.0,9.0,17.0,20.0,9.0,14
13,Illinois,IL,35,32,47,71,87,127,110,149,...,135.0,194.0,204.0,337.0,233.0,287.0,237.0,273.0,276.0,395
14,Indiana,IN,23,26,21,25,32,33,26,55,...,78.0,94.0,74.0,110.0,110.0,138.0,152.0,142.0,155.0,189
15,Iowa,IA,34,36,42,58,49,89,97,123,...,85.0,100.0,165.0,247.0,194.0,318.0,232.0,255.0,283.0,303
16,Kansas,KS,17,2,7,4,3,3,4,8,...,10.0,17.0,19.0,34.0,20.0,23.0,39.0,40.0,30.0,35
17,Kentucky,KY,13,23,25,17,15,5,7,6,...,5.0,3.0,14.0,40.0,44.0,49.0,33.0,20.0,22.0,22
18,Louisiana,LA,8,8,5,7,2,3,1,2,...,3.0,2.0,7.0,0.0,2.0,3.0,7.0,12.0,4.0,8
19,Maine,ME,71,108,219,175,225,247,338,529,...,751.0,1006.0,1111.0,1373.0,1401.0,1201.0,1487.0,1850.0,1405.0,2167
20,Maryland,MD,688,608,738,691,891,1235,1248,2576,...,1617.0,1351.0,1651.0,1197.0,1373.0,1728.0,1866.0,1891.0,1382.0,1417
21,Massachusetts,MA,1158,1164,1807,1532,1532,2336,1432,2988,...,3263.0,2476.0,5138.0,5290.0,5304.0,4224.0,198.0,410.0,16.0,7
22,Michigan,MI,23,21,26,12,27,62,55,51,...,95.0,104.0,98.0,168.0,127.0,148.0,221.0,291.0,262.0,413
23,Minnesota,MN,465,461,867,474,1023,917,914,1238,...,1960.0,2124.0,1515.0,2340.0,1416.0,1805.0,2126.0,2318.0,1541.0,1528
24,Mississippi,MS,3,8,12,21,0,0,3,1,...,0.0,5.0,1.0,0.0,2.0,4.0,1.0,1.0,4.0,4
25,Missouri,MO,47,37,41,70,25,15,5,10,...,4.0,8.0,2.0,3.0,10.0,5.0,10.0,12.0,11.0,17
26,Montana,MT,0,0,0,0,0,0,1,4,...,4.0,11.0,6.0,18.0,7.0,5.0,17.0,12.0,7.0,8
27,Nebraska,NE,5,4,6,2,2,2,11,7,...,8.0,11.0,15.0,10.0,7.0,11.0,14.0,14.0,15.0,10
28,Nevada,NV,4,4,2,3,1,3,4,15,...,2.0,5.0,10.0,16.0,6.0,7.0,15.0,17.0,14.0,17
29,New Hampshire,NH,84,129,261,190,226,265,617,896,...,1339.0,1299.0,1450.0,1687.0,724.0,529.0,891.0,1381.0,1428.0,1710
30,New Jersey,NJ,2459,2020,2349,2887,2698,3363,2432,3134,...,3712.0,4262.0,3576.0,3766.0,3286.0,4855.0,4350.0,5092.0,4000.0,3619
31,New Mexico,NM,0,1,1,1,1,3,3,5,...,5.0,6.0,1.0,6.0,0.0,0.0,1.0,3.0,2.0,7
32,New York,NY,4329,4083,5535,5399,5100,5565,4460,4165,...,3425.0,4490.0,2998.0,4615.0,3736.0,4314.0,3882.0,5155.0,3638.0,4243
33,North Carolina,NC,47,41,137,156,122,49,31,53,...,82.0,88.0,122.0,180.0,170.0,230.0,272.0,295.0,212.0,334
34,North Dakota,ND,2,0,1,0,0,3,7,12,...,33.0,27.0,15.0,29.0,14.0,33.0,32.0,56.0,33.0,38
35,Ohio,OH,61,44,82,66,50,58,43,33,...,44.0,53.0,67.0,93.0,119.0,154.0,160.0,270.0,293.0,467
36,Oklahoma,OK,1,0,0,0,3,0,0,1,...,0.0,2.0,4.0,3.0,0.0,0.0,0.0,1.0,0.0,0
37,Oregon,OR,13,15,12,16,11,3,7,6,...,39.0,38.0,48.0,43.0,45.0,31.0,61.0,84.0,70.0,65
38,Pennsylvania,PA,2343,2806,3989,5730,3985,4287,3242,3994,...,3805.0,5362.0,5033.0,5758.0,7487.0,9048.0,11443.0,11900.0,10208.0,8998
39,Rhode Island,RI,675,510,852,736,249,39,308,177,...,181.0,159.0,217.0,724.0,904.0,904.0,903.0,1132.0,1111.0,971
40,South Carolina,SC,25,6,26,18,22,15,20,31,...,29.0,37.0,44.0,42.0,37.0,42.0,51.0,21.0,39.0,47
41,South Dakota,SD,0,0,2,1,1,2,1,0,...,1.0,4.0,4.0,4.0,2.0,5.0,11.0,12.0,7.0,10
42,Tennessee,TN,28,31,28,20,20,8,15,31,...,36.0,37.0,30.0,25.0,17.0,26.0,25.0,47.0,29.0,45
43,Texas,TX,77,75,139,85,98,69,29,87,...,142.0,74.0,75.0,82.0,40.0,54.0,71.0,58.0,47.0,41
44,Utah,UT,3,1,5,2,1,2,5,7,...,3.0,9.0,5.0,15.0,13.0,7.0,19.0,25.0,27.0,19
45,Vermont,VT,40,18,37,43,50,54,105,138,...,356.0,623.0,522.0,893.0,599.0,710.0,761.0,1092.0,576.0,1064
46,Virginia,VA,149,156,259,195,216,274,357,959,...,1245.0,1023.0,1110.0,1307.0,1346.0,1539.0,1350.0,1657.0,1139.0,1199
47,Washington,WA,9,9,11,7,14,13,8,12,...,16.0,19.0,15.0,18.0,15.0,24.0,31.0,37.0,20.0,43
48,West Virginia,WV,35,16,26,31,38,61,28,84,...,145.0,118.0,97.0,143.0,136.0,289.0,368.0,648.0,671.0,885
49,Wisconsin,WI,631,597,1090,740,1144,1459,1466,1814,...,3488.0,3649.0,1766.0,1872.0,1361.0,1894.0,2295.0,3000.0,1869.0,2178
50,Wyoming,WY,3,1,2,2,4,3,1,3,...,0.0,2.0,4.0,3.0,3.0,1.0,1.0,4.0,0.0,5
51,Total,,8998,5730,5100,5565,4460,4165,7794,5722,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,7487

In [39]:
df.to_csv('df_add_total.csv')

In [40]:
!ls

 2022-DV-VS.py			      Lyme_Clean_Data.ipynb
 aggregated_states2.csv		      Lyme_Dash.png
 copy_2022-DV-VS.py		      maybe.csv
 data_complete_states.csv	      merged_comb.csv
 demo.py			     'merged_df _c.csv'
 df_add_total.csv		      merged_df.csv
 full_df.csv			      merged_new.csv
 full_df.ipynb			      spyder_df.csv
 LD-Case-Counts-by-County-00-19.csv   state_codes_us.csv
 Lyme_Clean_Data-Copy1.ipynb

In [30]:
cum2000

4329

In [28]:
df_add_column = pd.DataFrame(df,columns=['State', 'state_code', 'y2000', 'y2001', 'y2002', 'y2003', 'y2004',
       'y2005', 'y2006', 'y2007', 'y2008', 'y2009', 'y2010', 'y2011', 'y2012',
       'y2013', 'y2014', 'y2015', 'y2016', 'y2017', 'y2018', 'y2019']) 
df.insert(22,"Count_Sum",['4329','4083', '5730', '5100', '5565','4460','4165','7794','5722','3805',
                          '5362','5138','5758','7487','9048','11443','11900','10208','8998',],True)
df.columns

ValueError: Length of values (19) does not match length of index (51)

In [15]:
cummulated = pd.read_csv('spyder_df.csv')